name: update awesome-stars
on:
  schedule:
  - cron: 0 6 * * *
  workflow_dispatch:
jobs:
  awesome-stars:
    name: update awesome-stars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.0'
    - run: go install github.com/juev/starred@latest
    - name: update repo
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: starred --username juev --repository awesome-stars --sort --token ${GITHUB_TOKEN} --message 'update stars'
