name: update awesome-stars
on:
  schedule:
  - cron: 0 6 * * *
jobs:
  awesome-stars:
    name: update awesome-stars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: robinraju/release-downloader@v1.3
      with:
        repository: "juev/starred"
        latest: true
        fileName: "*"
    - name: unpack starred
      run: tar xfz starred_*_Linux_x86_64.tar.gz
    - name: update repo
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: ./starred --username juev --repository awesome-stars --sort --token ${GITHUB_TOKEN} --message 'update stars'
